package ch.sbb.compose_mds.sbbicons.small

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType.Companion.EvenOdd
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap.Companion.Butt
import androidx.compose.ui.graphics.StrokeJoin.Companion.Miter
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.ImageVector.Builder
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import ch.sbb.compose_mds.sbbicons.SmallGroup

public val SmallGroup.QrcodeDisabledSmall: ImageVector
    get() {
        if (_qrcodeDisabledSmall != null) {
            return _qrcodeDisabledSmall!!
        }
        _qrcodeDisabledSmall = Builder(name = "QrcodeDisabledSmall", defaultWidth = 24.0.dp,
                defaultHeight = 24.0.dp, viewportWidth = 24.0f, viewportHeight = 24.0f).apply {
            path(fill = SolidColor(Color(0xFF000000)), stroke = null, strokeLineWidth = 0.0f,
                    strokeLineCap = Butt, strokeLineJoin = Miter, strokeLineMiter = 4.0f,
                    pathFillType = EvenOdd) {
                moveToRelative(20.398f, 21.005f)
                lineToRelative(0.249f, 0.249f)
                lineToRelative(0.248f, -0.25f)
                lineTo(21.0f, 21.004f)
                lineTo(21.0f, 20.9f)
                lineToRelative(0.354f, -0.353f)
                lineToRelative(-17.9f, -17.9f)
                lineToRelative(-0.35f, 0.348f)
                lineTo(3.0f, 2.995f)
                verticalLineToRelative(0.106f)
                lineToRelative(-0.252f, 0.253f)
                lineToRelative(0.252f, 0.252f)
                verticalLineToRelative(1.397f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-0.397f)
                lineToRelative(1.0f, 1.0f)
                lineTo(5.0f, 6.0f)
                horizontalLineToRelative(0.395f)
                lineToRelative(0.605f, 0.606f)
                verticalLineToRelative(1.397f)
                horizontalLineToRelative(1.0f)
                lineTo(7.0f, 9.0f)
                lineTo(5.0f, 9.0f)
                lineTo(5.0f, 7.0f)
                lineTo(4.0f, 7.0f)
                lineTo(4.0f, 6.0f)
                lineTo(3.0f, 6.0f)
                verticalLineToRelative(2.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(2.0f)
                verticalLineToRelative(-0.999f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-0.395f)
                lineToRelative(1.0f, 1.001f)
                lineTo(9.0f, 15.0f)
                horizontalLineToRelative(5.393f)
                lineToRelative(1.002f, 1.002f)
                lineToRelative(-2.395f, 0.002f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(2.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-1.002f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(2.0f)
                horizontalLineToRelative(2.0f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(-1.395f)
                lineToRelative(2.0f, 2.0f)
                verticalLineToRelative(0.395f)
                horizontalLineToRelative(0.395f)
                lineToRelative(1.0f, 1.0f)
                lineTo(19.0f, 20.002f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(0.003f)
                close()
                moveTo(13.393f, 14.0f)
                lineToRelative(-1.0f, -1.0f)
                lineTo(11.0f, 13.0f)
                verticalLineToRelative(-1.393f)
                lineToRelative(-1.0f, -1.0f)
                lineTo(10.0f, 14.0f)
                close()
                moveTo(7.394f, 8.0f)
                lineToRelative(-0.395f, -0.395f)
                verticalLineToRelative(0.395f)
                close()
                moveTo(6.999f, 3.585f)
                verticalLineToRelative(-0.591f)
                lineTo(10.0f, 2.994f)
                verticalLineToRelative(1.0f)
                lineTo(7.41f, 3.994f)
                close()
                moveTo(14.0f, 10.585f)
                lineTo(14.0f, 10.0f)
                horizontalLineToRelative(-0.586f)
                lineToRelative(-1.0f, -1.0f)
                lineTo(15.0f, 9.0f)
                verticalLineToRelative(2.586f)
                close()
                moveTo(9.0f, 5.001f)
                verticalLineToRelative(0.002f)
                horizontalLineToRelative(-0.583f)
                lineToRelative(0.998f, 0.998f)
                lineTo(11.0f, 6.001f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(0.002f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(2.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-1.0f)
                lineToRelative(3.0f, -0.002f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(-0.998f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(1.998f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(-0.998f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(-2.0f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(0.998f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(1.0f)
                close()
                moveTo(20.0f, 7.003f)
                horizontalLineToRelative(1.0f)
                lineTo(21.0f, 6.002f)
                horizontalLineToRelative(-1.0f)
                close()
                moveTo(18.0f, 12.003f)
                verticalLineToRelative(0.998f)
                horizontalLineToRelative(-1.585f)
                lineTo(16.0f, 12.586f)
                verticalLineToRelative(-0.585f)
                horizontalLineToRelative(2.0f)
                verticalLineToRelative(-0.998f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(1.0f)
                close()
                moveTo(19.0f, 14.003f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(1.583f)
                lineToRelative(-1.0f, -1.0f)
                verticalLineToRelative(-0.582f)
                horizontalLineToRelative(-0.582f)
                lineTo(18.0f, 14.586f)
                verticalLineToRelative(-1.582f)
                horizontalLineToRelative(3.0f)
                verticalLineToRelative(2.0f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(-1.0f)
                close()
                moveTo(17.0f, 8.001f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(0.002f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(-2.0f)
                horizontalLineToRelative(1.0f)
                close()
                moveTo(17.0f, 21.005f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-2.0f)
                horizontalLineToRelative(-1.0f)
                close()
                moveTo(20.0f, 5.003f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-2.0f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(-0.002f)
                horizontalLineToRelative(-2.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(2.0f)
                close()
                moveTo(21.0f, 17.586f)
                lineTo(20.416f, 17.002f)
                lineTo(21.0f, 17.002f)
                close()
                moveTo(20.0f, 12.004f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-2.001f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(-1.0f)
                lineToRelative(1.0f, -0.002f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(-2.0f)
                verticalLineToRelative(2.002f)
                horizontalLineToRelative(1.0f)
                close()
                moveTo(19.0f, 7.001f)
                horizontalLineToRelative(-2.0f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(2.0f)
                close()
                moveTo(11.0f, 21.002f)
                verticalLineToRelative(-1.001f)
                horizontalLineToRelative(2.0f)
                verticalLineToRelative(1.001f)
                close()
                moveTo(12.0f, 8.003f)
                verticalLineToRelative(-2.0f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(0.998f)
                horizontalLineToRelative(-0.585f)
                lineToRelative(1.002f, 1.002f)
                close()
                moveTo(9.0f, 19.002f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-0.997f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(2.0f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(-0.003f)
                lineTo(9.0f, 20.002f)
                close()
                moveTo(15.0f, 19.005f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(2.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-0.003f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(-1.0f)
                close()
                moveTo(6.0f, 16.004f)
                verticalLineToRelative(-1.0f)
                lineToRelative(2.0f, -0.002f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(1.0f)
                lineTo(7.0f, 17.002f)
                verticalLineToRelative(-0.998f)
                close()
                moveTo(10.0f, 16.002f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(2.0f)
                verticalLineToRelative(-1.0f)
                close()
                moveTo(18.0f, 11.001f)
                horizontalLineToRelative(-2.0f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(2.0f)
                close()
                moveTo(3.0f, 18.001f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-1.0f)
                lineTo(3.0f, 17.001f)
                close()
                moveTo(6.0f, 13.001f)
                lineTo(5.0f, 13.001f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-0.997f)
                horizontalLineToRelative(2.0f)
                verticalLineToRelative(1.0f)
                lineTo(6.0f, 12.004f)
                close()
                moveTo(4.0f, 12.001f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-1.0f)
                lineTo(4.0f, 11.001f)
                verticalLineToRelative(-2.0f)
                lineTo(3.0f, 9.001f)
                verticalLineToRelative(2.0f)
                horizontalLineToRelative(1.0f)
                close()
                moveTo(4.0f, 12.001f)
                lineTo(3.0f, 12.001f)
                verticalLineToRelative(2.001f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(1.0f)
                lineToRelative(-1.0f, 0.002f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(2.0f)
                verticalLineToRelative(-2.002f)
                lineTo(4.0f, 14.002f)
                close()
                moveTo(15.0f, 8.002f)
                horizontalLineToRelative(-1.0f)
                lineTo(14.0f, 7.001f)
                horizontalLineToRelative(1.0f)
                close()
                moveTo(7.0f, 18.003f)
                lineTo(5.0f, 18.003f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(2.0f)
                close()
                moveTo(7.0f, 19.003f)
                verticalLineToRelative(-0.999f)
                horizontalLineToRelative(2.0f)
                verticalLineToRelative(1.0f)
                lineTo(8.0f, 19.004f)
                verticalLineToRelative(1.998f)
                lineTo(7.0f, 21.002f)
                verticalLineToRelative(-0.997f)
                lineTo(6.0f, 20.005f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(1.0f)
                close()
                moveTo(4.0f, 20.005f)
                horizontalLineToRelative(2.0f)
                verticalLineToRelative(1.0f)
                lineTo(4.0f, 21.005f)
                verticalLineToRelative(-0.003f)
                lineTo(3.0f, 21.002f)
                verticalLineToRelative(-2.0f)
                horizontalLineToRelative(1.0f)
                close()
                moveTo(8.0f, 14.004f)
                lineTo(6.0f, 14.004f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(2.0f)
                close()
            }
        }
        .build()
        return _qrcodeDisabledSmall!!
    }

private var _qrcodeDisabledSmall: ImageVector? = null
