package ch.sbb.compose_mds.sbbicons.small

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType.Companion.EvenOdd
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap.Companion.Butt
import androidx.compose.ui.graphics.StrokeJoin.Companion.Miter
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.ImageVector.Builder
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import ch.sbb.compose_mds.sbbicons.SmallGroup

public val SmallGroup.QrcodeDisabledTwoTicketsSmall: ImageVector
    get() {
        if (_qrcodeDisabledTwoTicketsSmall != null) {
            return _qrcodeDisabledTwoTicketsSmall!!
        }
        _qrcodeDisabledTwoTicketsSmall = Builder(name = "QrcodeDisabledTwoTicketsSmall",
                defaultWidth = 24.0.dp, defaultHeight = 24.0.dp, viewportWidth = 24.0f,
                viewportHeight = 24.0f).apply {
            path(fill = SolidColor(Color(0xFF000000)), stroke = null, strokeLineWidth = 0.0f,
                    strokeLineCap = Butt, strokeLineJoin = Miter, strokeLineMiter = 4.0f,
                    pathFillType = EvenOdd) {
                moveToRelative(21.354f, 20.647f)
                lineToRelative(-18.0f, -18.0f)
                lineTo(3.0f, 3.0f)
                lineToRelative(-0.354f, 0.354f)
                lineToRelative(0.354f, 0.353f)
                lineTo(3.0f, 6.0f)
                horizontalLineToRelative(1.0f)
                lineTo(4.0f, 4.707f)
                lineToRelative(3.0f, 3.0f)
                lineTo(7.0f, 10.0f)
                horizontalLineToRelative(1.0f)
                lineTo(8.0f, 8.707f)
                lineTo(9.29f, 9.998f)
                horizontalLineToRelative(-0.292f)
                verticalLineToRelative(1.0f)
                lineTo(7.0f, 10.998f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(2.0f)
                verticalLineToRelative(-1.0f)
                lineTo(10.0f, 10.998f)
                verticalLineToRelative(-0.29f)
                lineToRelative(1.0f, 1.0f)
                lineTo(11.0f, 17.0f)
                horizontalLineToRelative(5.293f)
                lineToRelative(1.0f, 1.0f)
                lineToRelative(-2.292f, 0.001f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(2.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-1.003f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(2.0f)
                horizontalLineToRelative(2.0f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(-1.29f)
                lineToRelative(2.0f, 2.0f)
                verticalLineToRelative(0.29f)
                horizontalLineToRelative(0.29f)
                lineToRelative(0.355f, 0.356f)
                close()
                moveTo(15.293f, 16.0f)
                lineToRelative(-1.003f, -1.003f)
                lineTo(13.0f, 14.997f)
                verticalLineToRelative(-1.29f)
                lineToRelative(-1.0f, -1.0f)
                lineTo(12.0f, 16.0f)
                close()
                moveTo(3.0f, 7.996f)
                horizontalLineToRelative(2.001f)
                verticalLineToRelative(-1.0f)
                lineTo(3.0f, 6.996f)
                close()
                moveTo(10.0f, 5.0f)
                lineTo(9.0f, 5.0f)
                lineTo(9.0f, 4.0f)
                horizontalLineToRelative(1.0f)
                close()
                moveTo(11.001f, 5.0f)
                horizontalLineToRelative(1.0f)
                lineTo(12.001f, 3.0f)
                horizontalLineToRelative(-1.0f)
                close()
                moveTo(15.001f, 4.998f)
                horizontalLineToRelative(-2.0f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(2.0f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(2.0f)
                verticalLineToRelative(2.0f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(-1.0f)
                close()
                moveTo(3.0f, 17.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-2.0f)
                lineTo(3.0f, 15.0f)
                close()
                moveTo(4.0f, 10.998f)
                lineTo(3.0f, 10.998f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(1.0f)
                lineTo(4.0f, 9.0f)
                horizontalLineToRelative(1.001f)
                verticalLineToRelative(1.0f)
                lineTo(4.0f, 10.0f)
                close()
                moveTo(3.0f, 12.998f)
                horizontalLineToRelative(1.0f)
                lineTo(4.0f, 12.0f)
                horizontalLineToRelative(1.001f)
                verticalLineToRelative(-1.0f)
                lineTo(4.0f, 11.0f)
                verticalLineToRelative(0.996f)
                lineTo(3.0f, 11.996f)
                close()
                moveTo(4.0f, 14.0f)
                horizontalLineToRelative(1.001f)
                verticalLineToRelative(-1.0f)
                lineTo(4.0f, 13.0f)
                close()
                moveTo(21.001f, 13.0f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(0.998f)
                horizontalLineToRelative(-2.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(2.0f)
                lineTo(20.001f, 14.0f)
                horizontalLineToRelative(1.0f)
                close()
                moveTo(20.001f, 11.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(0.998f)
                horizontalLineToRelative(-2.0f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(2.0f)
                close()
                moveTo(15.0f, 9.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(0.998f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(-1.0f)
                lineTo(16.0f, 7.0f)
                horizontalLineToRelative(-1.0f)
                close()
                moveTo(21.001f, 17.0f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(-2.0f)
                horizontalLineToRelative(1.0f)
                close()
                moveTo(13.002f, 21.001f)
                horizontalLineToRelative(-1.001f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(1.001f)
                close()
                moveTo(6.999f, 21.001f)
                horizontalLineToRelative(1.0f)
                lineTo(7.999f, 19.0f)
                lineTo(7.0f, 19.0f)
                close()
                moveTo(8.999f, 16.998f)
                horizontalLineToRelative(1.0f)
                lineToRelative(0.002f, 1.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(1.0f)
                lineTo(9.0f, 18.998f)
                lineTo(9.0f, 18.0f)
                lineTo(8.0f, 18.0f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(1.0f)
                close()
                moveTo(12.001f, 18.998f)
                horizontalLineToRelative(2.001f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(-2.001f)
                close()
                moveTo(6.999f, 14.998f)
                horizontalLineToRelative(1.0f)
                lineTo(7.999f, 14.0f)
                lineTo(10.0f, 14.0f)
                verticalLineToRelative(-1.0f)
                lineTo(8.0f, 13.0f)
                verticalLineToRelative(0.998f)
                lineTo(7.0f, 13.998f)
                close()
                moveTo(7.999f, 16.998f)
                lineTo(7.0f, 16.998f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(1.0f)
                lineTo(8.0f, 15.0f)
                lineTo(10.0f, 15.0f)
                verticalLineToRelative(1.0f)
                lineTo(8.0f, 16.0f)
                close()
                moveTo(20.001f, 8.998f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-2.0f)
                horizontalLineToRelative(-2.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(1.0f)
                close()
                moveTo(11.001f, 21.001f)
                lineTo(8.998f, 21.001f)
                verticalLineToRelative(-1.0f)
                lineTo(11.0f, 20.001f)
                close()
                moveTo(18.001f, 11.001f)
                lineTo(18.001f, 9.0f)
                lineToRelative(-1.0f, -0.003f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(2.0f)
                verticalLineToRelative(2.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(1.0f)
                close()
                moveTo(14.996f, 11.996f)
                lineTo(16.0f, 11.996f)
                lineTo(16.0f, 13.0f)
                lineToRelative(1.0f, 1.0f)
                verticalLineToRelative(-3.003f)
                horizontalLineToRelative(-3.003f)
                close()
                moveTo(13.0f, 9.998f)
                horizontalLineToRelative(-0.002f)
                lineTo(12.0f, 9.0f)
                verticalLineToRelative(-0.002f)
                horizontalLineToRelative(1.0f)
                lineTo(13.0f, 8.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(2.0f)
                horizontalLineToRelative(-1.0f)
                close()
                moveTo(11.0f, 8.0f)
                verticalLineToRelative(-0.001f)
                horizontalLineToRelative(2.0f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(-3.0f)
                close()
                moveTo(7.0f, 3.998f)
                lineTo(7.0f, 4.0f)
                lineTo(6.0f, 3.0f)
                verticalLineToRelative(-0.002f)
                horizontalLineToRelative(3.0f)
                verticalLineToRelative(1.0f)
                close()
            }
        }
        .build()
        return _qrcodeDisabledTwoTicketsSmall!!
    }

private var _qrcodeDisabledTwoTicketsSmall: ImageVector? = null
