package ch.sbb.compose_mds.sbbicons.small

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType.Companion.EvenOdd
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap.Companion.Butt
import androidx.compose.ui.graphics.StrokeJoin.Companion.Miter
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.ImageVector.Builder
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import ch.sbb.compose_mds.sbbicons.SmallGroup

public val SmallGroup.QrcodeTwoTicketsSmall: ImageVector
    get() {
        if (_qrcodeTwoTicketsSmall != null) {
            return _qrcodeTwoTicketsSmall!!
        }
        _qrcodeTwoTicketsSmall = Builder(name = "QrcodeTwoTicketsSmall", defaultWidth = 24.0.dp,
                defaultHeight = 24.0.dp, viewportWidth = 24.0f, viewportHeight = 24.0f).apply {
            path(fill = SolidColor(Color(0xFF000000)), stroke = null, strokeLineWidth = 0.0f,
                    strokeLineCap = Butt, strokeLineJoin = Miter, strokeLineMiter = 4.0f,
                    pathFillType = EvenOdd) {
                moveTo(3.0f, 3.0f)
                verticalLineToRelative(3.0f)
                horizontalLineToRelative(1.0f)
                lineTo(4.0f, 3.996f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-1.0f)
                lineTo(3.0f, 2.996f)
                close()
                moveTo(3.0f, 7.996f)
                horizontalLineToRelative(2.001f)
                verticalLineToRelative(-1.0f)
                lineTo(3.0f, 6.996f)
                close()
                moveTo(10.0f, 5.0f)
                lineTo(8.999f, 5.0f)
                verticalLineToRelative(-1.0f)
                lineTo(10.0f, 4.0f)
                close()
                moveTo(11.001f, 5.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-2.0f)
                horizontalLineToRelative(-1.0f)
                close()
                moveTo(6.0f, 2.997f)
                horizontalLineToRelative(3.0f)
                verticalLineToRelative(1.0f)
                lineTo(7.0f, 3.997f)
                lineTo(7.0f, 5.0f)
                lineTo(5.0f, 5.0f)
                lineTo(5.0f, 4.0f)
                horizontalLineToRelative(1.0f)
                lineTo(6.0f, 2.997f)
                moveToRelative(7.001f, 2.0f)
                horizontalLineToRelative(2.0f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-2.0f)
                horizontalLineToRelative(-2.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(-2.0f)
                close()
                moveTo(4.0f, 17.0f)
                lineTo(3.0f, 17.0f)
                verticalLineToRelative(-2.0f)
                horizontalLineToRelative(1.0f)
                close()
                moveTo(3.0f, 10.998f)
                horizontalLineToRelative(1.0f)
                lineTo(4.0f, 10.0f)
                horizontalLineToRelative(1.001f)
                lineTo(5.001f, 9.0f)
                lineTo(4.0f, 9.0f)
                verticalLineToRelative(0.998f)
                lineTo(3.0f, 9.998f)
                close()
                moveTo(4.0f, 12.998f)
                lineTo(3.0f, 12.998f)
                verticalLineToRelative(-1.002f)
                horizontalLineToRelative(1.0f)
                lineTo(4.0f, 11.0f)
                horizontalLineToRelative(1.001f)
                verticalLineToRelative(1.0f)
                lineTo(4.0f, 12.0f)
                close()
                moveTo(5.001f, 14.0f)
                lineTo(4.0f, 14.0f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(1.001f)
                close()
                moveTo(11.0f, 16.997f)
                horizontalLineToRelative(6.0f)
                verticalLineToRelative(-6.0f)
                horizontalLineToRelative(-6.0f)
                close()
                moveTo(12.0f, 15.997f)
                horizontalLineToRelative(4.0f)
                verticalLineToRelative(-4.0f)
                horizontalLineToRelative(-4.0f)
                close()
                moveTo(15.0f, 14.997f)
                horizontalLineToRelative(-2.0f)
                verticalLineToRelative(-2.0f)
                horizontalLineToRelative(2.0f)
                close()
                moveTo(6.999f, 11.997f)
                horizontalLineToRelative(2.0f)
                verticalLineToRelative(-0.999f)
                lineTo(10.0f, 10.998f)
                verticalLineToRelative(-1.0f)
                lineTo(8.999f, 9.998f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(-2.0f)
                close()
                moveTo(14.001f, 9.998f)
                lineTo(14.001f, 10.0f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(-0.002f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(1.0f)
                lineTo(13.001f, 8.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(1.998f)
                moveToRelative(7.0f, 3.002f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(0.998f)
                horizontalLineToRelative(-2.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(2.0f)
                lineTo(20.001f, 14.0f)
                horizontalLineToRelative(1.0f)
                close()
                moveTo(20.001f, 11.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(0.998f)
                horizontalLineToRelative(-2.0f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(2.0f)
                close()
                moveTo(10.999f, 9.0f)
                lineTo(10.999f, 7.998f)
                horizontalLineToRelative(2.002f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(-3.0f)
                lineTo(10.001f, 7.0f)
                lineTo(10.0f, 7.0f)
                verticalLineToRelative(1.0f)
                lineTo(9.0f, 8.0f)
                verticalLineToRelative(1.0f)
                close()
                moveTo(16.0f, 9.0f)
                horizontalLineToRelative(-1.0f)
                lineTo(15.0f, 7.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(1.998f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(-1.0f)
                close()
                moveTo(20.001f, 17.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-2.0f)
                horizontalLineToRelative(-1.0f)
                close()
                moveTo(9.0f, 7.996f)
                lineTo(8.0f, 7.996f)
                lineTo(8.0f, 10.0f)
                lineTo(7.0f, 10.0f)
                lineTo(7.0f, 6.996f)
                horizontalLineToRelative(2.0f)
                close()
                moveTo(12.0f, 21.001f)
                horizontalLineToRelative(1.001f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(-1.001f)
                close()
                moveTo(7.998f, 21.001f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(-2.002f)
                horizontalLineToRelative(1.0f)
                close()
                moveTo(9.998f, 16.998f)
                lineTo(9.0f, 16.998f)
                lineTo(9.0f, 17.0f)
                lineTo(8.0f, 17.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(0.998f)
                horizontalLineToRelative(2.002f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(-1.0f)
                close()
                moveTo(14.001f, 18.998f)
                horizontalLineToRelative(-2.001f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(2.001f)
                close()
                moveTo(20.0f, 20.998f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(-1.0f)
                close()
                moveTo(7.998f, 14.998f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(1.0f)
                lineTo(7.998f, 13.0f)
                lineTo(10.0f, 13.0f)
                verticalLineToRelative(1.0f)
                lineTo(7.999f, 14.0f)
                close()
                moveTo(6.998f, 16.998f)
                horizontalLineToRelative(1.0f)
                lineTo(7.998f, 16.0f)
                lineTo(10.0f, 16.0f)
                verticalLineToRelative(-1.0f)
                lineTo(7.999f, 15.0f)
                verticalLineToRelative(0.998f)
                horizontalLineToRelative(-1.0f)
                close()
                moveTo(21.0f, 8.998f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(2.0f)
                verticalLineToRelative(2.0f)
                moveTo(8.999f, 21.0f)
                lineTo(11.0f, 21.0f)
                verticalLineToRelative(-1.0f)
                lineTo(8.999f, 20.0f)
                close()
                moveTo(20.001f, 18.997f)
                horizontalLineToRelative(-1.0f)
                lineTo(19.001f, 18.0f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(1.998f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(-2.0f)
                verticalLineToRelative(-2.0f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(1.003f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(-2.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-1.0f)
                lineToRelative(3.0f, -0.003f)
                lineTo(18.001f, 16.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(1.998f)
                horizontalLineToRelative(1.0f)
                close()
                moveTo(18.001f, 10.999f)
                lineTo(18.001f, 9.0f)
                lineToRelative(-1.0f, -0.002f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(2.0f)
                verticalLineToRelative(2.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(1.0f)
                close()
            }
        }
        .build()
        return _qrcodeTwoTicketsSmall!!
    }

private var _qrcodeTwoTicketsSmall: ImageVector? = null
