package ch.sbb.compose_mds.sbbicons.small

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType.Companion.EvenOdd
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap.Companion.Butt
import androidx.compose.ui.graphics.StrokeJoin.Companion.Miter
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.ImageVector.Builder
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import ch.sbb.compose_mds.sbbicons.SmallGroup

public val SmallGroup.TicketJourneySmall: ImageVector
    get() {
        if (_ticketJourneySmall != null) {
            return _ticketJourneySmall!!
        }
        _ticketJourneySmall = Builder(name = "TicketJourneySmall", defaultWidth = 24.0.dp,
                defaultHeight = 24.0.dp, viewportWidth = 24.0f, viewportHeight = 24.0f).apply {
            path(fill = SolidColor(Color(0xFF000000)), stroke = null, strokeLineWidth = 0.0f,
                    strokeLineCap = Butt, strokeLineJoin = Miter, strokeLineMiter = 4.0f,
                    pathFillType = EvenOdd) {
                moveTo(15.993f, 3.007f)
                arcToRelative(5.0f, 5.0f, 0.0f, false, false, -5.0f, 5.0f)
                verticalLineToRelative(0.019f)
                quadToRelative(0.024f, 0.58f, 0.174f, 1.094f)
                lineToRelative(0.961f, -0.278f)
                arcToRelative(3.5f, 3.5f, 0.0f, false, true, -0.135f, -0.844f)
                arcToRelative(4.0f, 4.0f, 0.0f, false, true, 8.0f, 0.007f)
                curveToRelative(-0.007f, 0.624f, -0.2f, 1.198f, -0.53f, 1.779f)
                lineToRelative(-3.458f, 5.458f)
                lineToRelative(-0.603f, -0.952f)
                lineToRelative(-0.845f, 0.536f)
                lineToRelative(1.025f, 1.618f)
                lineToRelative(0.423f, 0.666f)
                lineToRelative(0.422f, -0.666f)
                lineToRelative(3.887f, -6.135f)
                lineToRelative(0.006f, -0.01f)
                lineToRelative(0.006f, -0.01f)
                curveToRelative(0.391f, -0.687f, 0.659f, -1.432f, 0.667f, -2.277f)
                verticalLineToRelative(-0.005f)
                arcToRelative(5.0f, 5.0f, 0.0f, false, false, -5.0f, -5.0f)
                moveToRelative(0.006f, 3.994f)
                arcToRelative(1.0f, 1.0f, 0.0f, true, false, -0.001f, 1.998f)
                arcToRelative(1.0f, 1.0f, 0.0f, false, false, 0.001f, -1.998f)
                moveToRelative(-2.0f, 1.0f)
                arcToRelative(2.0f, 2.0f, 0.0f, true, true, 3.999f, -0.002f)
                arcToRelative(2.0f, 2.0f, 0.0f, false, true, -3.999f, 0.002f)
                moveToRelative(-9.0f, 2.999f)
                lineTo(4.0f, 11.0f)
                verticalLineToRelative(0.993f)
                lineTo(2.993f, 11.993f)
                verticalLineToRelative(-2.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-0.001f)
                lineTo(5.0f, 9.992f)
                close()
                moveTo(3.992f, 20.994f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(-2.0f)
                lineTo(4.0f, 18.994f)
                verticalLineToRelative(0.999f)
                horizontalLineToRelative(1.0f)
                lineTo(5.0f, 21.0f)
                lineTo(3.992f, 21.0f)
                close()
                moveTo(6.992f, 18.993f)
                verticalLineToRelative(-1.0f)
                lineTo(5.0f, 17.993f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(-0.008f)
                lineTo(4.992f, 16.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(1.99f)
                horizontalLineToRelative(5.0f)
                verticalLineToRelative(-1.99f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(0.992f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(-2.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(2.0f)
                lineTo(10.992f, 20.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(1.0f)
                lineTo(13.0f, 21.0f)
                verticalLineToRelative(-0.007f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-2.0f)
                horizontalLineToRelative(-1.007f)
                verticalLineToRelative(0.999f)
                lineTo(12.0f, 19.992f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(-1.007f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(2.0f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-1.0f)
                lineTo(12.0f, 15.992f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(1.993f)
                verticalLineToRelative(-1.0f)
                lineTo(13.0f, 13.992f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(-1.007f)
                lineTo(11.993f, 12.0f)
                lineTo(12.0f, 12.0f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(0.993f)
                verticalLineToRelative(0.993f)
                lineTo(14.0f, 11.993f)
                verticalLineToRelative(-2.0f)
                lineTo(13.0f, 9.993f)
                verticalLineToRelative(-0.001f)
                horizontalLineToRelative(-1.008f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(1.0f)
                lineTo(9.0f, 12.992f)
                verticalLineToRelative(-1.0f)
                lineTo(7.992f, 11.992f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(-2.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(1.009f)
                lineTo(4.0f, 15.001f)
                verticalLineToRelative(-1.008f)
                horizontalLineToRelative(1.992f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(-2.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(1.0f)
                lineTo(3.992f, 18.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(0.992f)
                close()
                moveTo(6.992f, 18.993f)
                lineTo(8.0f, 18.993f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(1.993f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(-2.0f)
                lineTo(7.993f, 20.0f)
                lineTo(7.0f, 20.0f)
                verticalLineToRelative(1.0f)
                lineTo(5.992f, 21.0f)
                verticalLineToRelative(-1.008f)
                horizontalLineToRelative(1.0f)
                close()
                moveTo(6.0f, 12.992f)
                horizontalLineToRelative(1.992f)
                verticalLineToRelative(-1.0f)
                lineTo(6.0f, 11.992f)
                close()
                moveTo(10.992f, 14.992f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-1.999f)
                horizontalLineToRelative(-1.0f)
                close()
                moveTo(7.992f, 10.992f)
                horizontalLineToRelative(2.0f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(-2.0f)
                close()
                moveTo(7.992f, 16.001f)
                lineTo(9.0f, 16.001f)
                verticalLineToRelative(-1.008f)
                lineTo(7.992f, 14.993f)
                close()
                moveTo(9.992f, 16.991f)
                horizontalLineToRelative(-3.0f)
                verticalLineToRelative(-3.0f)
                horizontalLineToRelative(3.0f)
                close()
            }
        }
        .build()
        return _ticketJourneySmall!!
    }

private var _ticketJourneySmall: ImageVector? = null
