package ch.sbb.compose_mds.sbbicons.large

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType.Companion.EvenOdd
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap.Companion.Butt
import androidx.compose.ui.graphics.StrokeJoin.Companion.Miter
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.ImageVector.Builder
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import ch.sbb.compose_mds.sbbicons.LargeGroup

public val LargeGroup.ArmchairLarge: ImageVector
    get() {
        if (_armchairLarge != null) {
            return _armchairLarge!!
        }
        _armchairLarge = Builder(name = "ArmchairLarge", defaultWidth = 48.0.dp, defaultHeight =
                48.0.dp, viewportWidth = 48.0f, viewportHeight = 48.0f).apply {
            path(fill = SolidColor(Color(0xFF000000)), stroke = null, strokeLineWidth = 0.0f,
                    strokeLineCap = Butt, strokeLineJoin = Miter, strokeLineMiter = 4.0f,
                    pathFillType = EvenOdd) {
                moveTo(14.5f, 4.0f)
                arcTo(4.5f, 4.5f, 0.0f, false, false, 10.0f, 8.5f)
                verticalLineToRelative(7.725f)
                arcToRelative(5.7f, 5.7f, 0.0f, false, false, -0.937f, -0.201f)
                horizontalLineToRelative(-0.006f)
                arcTo(5.5f, 5.5f, 0.0f, false, false, 7.0f, 26.797f)
                lineTo(7.0f, 33.5f)
                arcToRelative(3.5f, 3.5f, 0.0f, false, false, 3.5f, 3.5f)
                horizontalLineToRelative(0.5f)
                verticalLineToRelative(4.0f)
                arcToRelative(2.0f, 2.0f, 0.0f, false, false, 2.0f, 2.0f)
                horizontalLineToRelative(1.0f)
                arcToRelative(2.0f, 2.0f, 0.0f, false, false, 2.0f, -2.0f)
                verticalLineToRelative(-4.0f)
                horizontalLineToRelative(17.0f)
                verticalLineToRelative(4.0f)
                arcToRelative(2.0f, 2.0f, 0.0f, false, false, 2.0f, 2.0f)
                horizontalLineToRelative(1.0f)
                arcToRelative(2.0f, 2.0f, 0.0f, false, false, 2.0f, -2.0f)
                verticalLineToRelative(-4.036f)
                arcToRelative(3.5f, 3.5f, 0.0f, false, false, 3.0f, -3.464f)
                verticalLineToRelative(-6.702f)
                arcToRelative(5.5f, 5.5f, 0.0f, false, false, -2.057f, -10.775f)
                horizontalLineToRelative(-0.005f)
                quadToRelative(-0.48f, 0.061f, -0.938f, 0.2f)
                lineTo(38.0f, 8.5f)
                arcTo(4.5f, 4.5f, 0.0f, false, false, 33.5f, 4.0f)
                close()
                moveTo(37.0f, 16.635f)
                lineTo(37.0f, 8.5f)
                arcTo(3.5f, 3.5f, 0.0f, false, false, 33.5f, 5.0f)
                horizontalLineToRelative(-19.0f)
                arcTo(3.5f, 3.5f, 0.0f, false, false, 11.0f, 8.5f)
                verticalLineToRelative(8.139f)
                arcToRelative(5.65f, 5.65f, 0.0f, false, true, 3.0f, 5.079f)
                lineTo(14.0f, 26.0f)
                horizontalLineToRelative(20.0f)
                verticalLineToRelative(-4.282f)
                horizontalLineToRelative(-0.01f)
                arcTo(5.65f, 5.65f, 0.0f, false, true, 37.0f, 16.635f)
                moveToRelative(-2.51f, 5.075f)
                lineTo(35.0f, 21.71f)
                verticalLineToRelative(5.79f)
                arcToRelative(3.5f, 3.5f, 0.0f, false, true, -3.5f, 3.5f)
                horizontalLineToRelative(-15.0f)
                arcToRelative(3.5f, 3.5f, 0.0f, false, true, -3.5f, -3.5f)
                verticalLineToRelative(-5.79f)
                horizontalLineToRelative(0.5f)
                lineToRelative(-0.5f, -0.008f)
                arcToRelative(4.65f, 4.65f, 0.0f, false, false, -4.06f, -4.686f)
                arcToRelative(4.5f, 4.5f, 0.0f, false, false, -1.347f, 8.893f)
                lineToRelative(0.407f, 0.077f)
                lineTo(8.0f, 33.5f)
                arcToRelative(2.5f, 2.5f, 0.0f, false, false, 2.5f, 2.5f)
                horizontalLineToRelative(27.0f)
                arcToRelative(2.5f, 2.5f, 0.0f, false, false, 2.5f, -2.5f)
                verticalLineToRelative(-7.514f)
                lineToRelative(0.407f, -0.077f)
                arcToRelative(4.5f, 4.5f, 0.0f, false, false, -1.347f, -8.892f)
                arcToRelative(4.65f, 4.65f, 0.0f, false, false, -4.07f, 4.685f)
                close()
                moveTo(37.0f, 37.0f)
                horizontalLineToRelative(-3.0f)
                verticalLineToRelative(4.0f)
                arcToRelative(1.0f, 1.0f, 0.0f, false, false, 1.0f, 1.0f)
                horizontalLineToRelative(1.0f)
                arcToRelative(1.0f, 1.0f, 0.0f, false, false, 1.0f, -1.0f)
                close()
                moveTo(15.0f, 37.0f)
                horizontalLineToRelative(-3.0f)
                verticalLineToRelative(4.0f)
                arcToRelative(1.0f, 1.0f, 0.0f, false, false, 1.0f, 1.0f)
                horizontalLineToRelative(1.0f)
                arcToRelative(1.0f, 1.0f, 0.0f, false, false, 1.0f, -1.0f)
                close()
                moveTo(18.0f, 9.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(-1.0f)
                lineTo(19.0f, 9.0f)
                close()
                moveTo(8.5f, 20.0f)
                arcToRelative(1.5f, 1.5f, 0.0f, true, false, 0.0f, 3.0f)
                arcToRelative(1.5f, 1.5f, 0.0f, false, false, 0.0f, -3.0f)
                moveTo(6.0f, 21.5f)
                arcToRelative(2.5f, 2.5f, 0.0f, true, true, 5.0f, 0.0f)
                arcToRelative(2.5f, 2.5f, 0.0f, false, true, -5.0f, 0.0f)
                moveToRelative(32.0f, 0.0f)
                arcToRelative(1.5f, 1.5f, 0.0f, true, true, 3.0f, 0.0f)
                arcToRelative(1.5f, 1.5f, 0.0f, false, true, -3.0f, 0.0f)
                moveToRelative(1.5f, -2.5f)
                arcToRelative(2.5f, 2.5f, 0.0f, true, false, 0.0f, 5.0f)
                arcToRelative(2.5f, 2.5f, 0.0f, false, false, 0.0f, -5.0f)
                moveTo(34.0f, 27.0f)
                lineTo(14.0f, 27.0f)
                verticalLineToRelative(0.5f)
                arcToRelative(2.5f, 2.5f, 0.0f, false, false, 2.5f, 2.5f)
                horizontalLineToRelative(15.0f)
                arcToRelative(2.5f, 2.5f, 0.0f, false, false, 2.5f, -2.5f)
                close()
                moveTo(18.0f, 19.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(-1.0f)
                close()
                moveTo(29.0f, 9.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(-1.0f)
                lineTo(30.0f, 9.0f)
                close()
                moveTo(29.0f, 19.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(1.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-1.0f)
                horizontalLineToRelative(-1.0f)
                verticalLineToRelative(-1.0f)
                close()
            }
        }
        .build()
        return _armchairLarge!!
    }

private var _armchairLarge: ImageVector? = null
