package ch.sbb.compose_mds.sbbicons.medium

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType.Companion.EvenOdd
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap.Companion.Butt
import androidx.compose.ui.graphics.StrokeJoin.Companion.Miter
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.ImageVector.Builder
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import ch.sbb.compose_mds.sbbicons.MediumGroup

public val MediumGroup.DocumentZipMedium: ImageVector
    get() {
        if (_documentZipMedium != null) {
            return _documentZipMedium!!
        }
        _documentZipMedium = Builder(name = "DocumentZipMedium", defaultWidth = 36.0.dp,
                defaultHeight = 36.0.dp, viewportWidth = 36.0f, viewportHeight = 36.0f).apply {
            path(fill = SolidColor(Color(0xFF000000)), stroke = null, strokeLineWidth = 0.0f,
                    strokeLineCap = Butt, strokeLineJoin = Miter, strokeLineMiter = 4.0f,
                    pathFillType = EvenOdd) {
                moveTo(9.75f, 6.25f)
                horizontalLineToRelative(-0.5f)
                verticalLineToRelative(23.5f)
                horizontalLineToRelative(17.5f)
                lineTo(26.75f, 14.043f)
                lineToRelative(-0.146f, -0.146f)
                lineToRelative(-7.5f, -7.5f)
                lineToRelative(-0.147f, -0.147f)
                lineTo(9.75f, 6.25f)
                moveToRelative(0.5f, 22.5f)
                lineTo(10.25f, 7.25f)
                horizontalLineToRelative(8.0f)
                verticalLineToRelative(7.5f)
                horizontalLineToRelative(7.5f)
                verticalLineToRelative(14.0f)
                close()
                moveTo(25.043f, 13.75f)
                lineTo(19.25f, 7.959f)
                verticalLineToRelative(5.793f)
                close()
                moveTo(12.25f, 7.989f)
                lineTo(12.25f, 7.5f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(0.488f)
                close()
                moveTo(12.25f, 9.939f)
                verticalLineToRelative(-0.975f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(0.975f)
                close()
                moveTo(12.25f, 11.889f)
                verticalLineToRelative(-0.975f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(0.975f)
                close()
                moveTo(12.25f, 13.839f)
                verticalLineToRelative(-0.975f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(0.975f)
                close()
                moveTo(12.25f, 15.789f)
                verticalLineToRelative(-0.975f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(0.975f)
                close()
                moveTo(12.25f, 17.739f)
                verticalLineToRelative(-0.975f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(0.975f)
                close()
                moveTo(12.25f, 19.689f)
                verticalLineToRelative(-0.975f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(0.975f)
                close()
                moveTo(12.25f, 21.639f)
                verticalLineToRelative(-0.975f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(0.975f)
                close()
                moveTo(12.25f, 23.589f)
                verticalLineToRelative(-0.975f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(0.975f)
                close()
                moveTo(12.25f, 25.539f)
                verticalLineToRelative(-0.975f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(0.975f)
                close()
                moveTo(12.25f, 27.001f)
                verticalLineToRelative(-0.487f)
                horizontalLineToRelative(1.0f)
                lineTo(13.25f, 27.0f)
                close()
                moveTo(13.75f, 9.001f)
                verticalLineToRelative(0.488f)
                horizontalLineToRelative(1.0f)
                lineTo(14.75f, 9.0f)
                close()
                moveTo(13.75f, 10.464f)
                verticalLineToRelative(0.975f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-0.975f)
                close()
                moveTo(13.75f, 12.414f)
                verticalLineToRelative(0.975f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-0.975f)
                close()
                moveTo(13.75f, 14.364f)
                verticalLineToRelative(0.975f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-0.975f)
                close()
                moveTo(13.75f, 16.314f)
                verticalLineToRelative(0.975f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-0.975f)
                close()
                moveTo(13.75f, 18.264f)
                verticalLineToRelative(0.975f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-0.975f)
                close()
                moveTo(13.75f, 20.214f)
                verticalLineToRelative(0.975f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-0.975f)
                close()
                moveTo(13.75f, 22.164f)
                verticalLineToRelative(0.975f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-0.975f)
                close()
                moveTo(13.75f, 24.114f)
                verticalLineToRelative(0.975f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-0.975f)
                close()
                moveTo(13.75f, 26.064f)
                verticalLineToRelative(0.975f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-0.975f)
                close()
                moveTo(13.75f, 28.014f)
                verticalLineToRelative(0.487f)
                horizontalLineToRelative(1.0f)
                verticalLineToRelative(-0.487f)
                close()
            }
        }
        .build()
        return _documentZipMedium!!
    }

private var _documentZipMedium: ImageVector? = null
