package ch.sbb.compose_mds.sbbicons.medium

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType.Companion.EvenOdd
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap.Companion.Butt
import androidx.compose.ui.graphics.StrokeJoin.Companion.Miter
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.ImageVector.Builder
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import ch.sbb.compose_mds.sbbicons.MediumGroup

public val MediumGroup.QrcodeMedium: ImageVector
    get() {
        if (_qrcodeMedium != null) {
            return _qrcodeMedium!!
        }
        _qrcodeMedium = Builder(name = "QrcodeMedium", defaultWidth = 36.0.dp, defaultHeight =
                36.0.dp, viewportWidth = 36.0f, viewportHeight = 36.0f).apply {
            path(fill = SolidColor(Color(0xFF000000)), stroke = null, strokeLineWidth = 0.0f,
                    strokeLineCap = Butt, strokeLineJoin = Miter, strokeLineMiter = 4.0f,
                    pathFillType = EvenOdd) {
                moveTo(15.0f, 21.0f)
                horizontalLineToRelative(6.0f)
                verticalLineToRelative(-6.0f)
                horizontalLineToRelative(-6.0f)
                close()
                moveTo(13.5f, 22.5f)
                horizontalLineToRelative(9.0f)
                verticalLineToRelative(-9.0f)
                horizontalLineToRelative(-9.0f)
                close()
                moveTo(16.5f, 19.5f)
                horizontalLineToRelative(3.0f)
                verticalLineToRelative(-3.0f)
                horizontalLineToRelative(-3.0f)
                close()
                moveTo(10.499f, 5.994f)
                lineTo(15.0f, 5.994f)
                lineTo(15.0f, 4.492f)
                horizontalLineToRelative(-4.501f)
                close()
                moveTo(10.499f, 8.999f)
                lineTo(10.499f, 7.5f)
                horizontalLineToRelative(-3.0f)
                lineTo(7.499f, 9.0f)
                lineToRelative(1.5f, 0.005f)
                verticalLineToRelative(3.0f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(3.0f)
                lineTo(13.499f, 9.001f)
                horizontalLineToRelative(3.0f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(-3.0f)
                verticalLineToRelative(0.003f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(-1.5f)
                close()
                moveTo(10.499f, 13.499f)
                lineTo(7.5f, 13.499f)
                verticalLineToRelative(-3.0f)
                lineTo(6.0f, 10.499f)
                lineTo(6.0f, 9.0f)
                lineTo(4.5f, 9.0f)
                verticalLineToRelative(3.0f)
                lineTo(6.0f, 12.0f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(1.499f)
                lineTo(7.499f, 15.0f)
                horizontalLineToRelative(3.0f)
                close()
                moveTo(17.999f, 7.505f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-3.0f)
                lineTo(18.0f, 4.505f)
                verticalLineToRelative(1.497f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(1.5f)
                lineTo(18.0f, 7.502f)
                close()
                moveTo(30.0f, 10.505f)
                horizontalLineToRelative(1.5f)
                lineTo(31.5f, 9.002f)
                lineTo(30.0f, 9.002f)
                close()
                moveTo(27.0f, 18.005f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-1.5f)
                lineTo(27.0f, 16.505f)
                verticalLineToRelative(1.497f)
                horizontalLineToRelative(-3.0f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(3.0f)
                close()
                moveTo(5.999f, 6.005f)
                lineTo(8.999f, 5.993f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(-4.5f)
                verticalLineToRelative(3.012f)
                horizontalLineToRelative(1.5f)
                close()
                moveTo(27.0f, 19.505f)
                verticalLineToRelative(3.0f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-1.5f)
                lineTo(30.0f, 21.005f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-3.0f)
                close()
                moveTo(19.5f, 7.505f)
                verticalLineToRelative(3.0f)
                lineTo(21.0f, 10.505f)
                verticalLineToRelative(-1.5f)
                lineToRelative(4.5f, -0.003f)
                verticalLineToRelative(-1.5f)
                lineTo(27.0f, 7.502f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(-1.5f)
                lineTo(25.5f, 4.505f)
                lineTo(24.0f, 4.505f)
                verticalLineToRelative(2.997f)
                horizontalLineToRelative(-1.5f)
                lineTo(22.5f, 6.005f)
                lineTo(21.0f, 6.005f)
                verticalLineToRelative(1.5f)
                close()
                moveTo(24.0f, 10.505f)
                verticalLineToRelative(3.0f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-0.003f)
                lineTo(27.0f, 13.502f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(-1.497f)
                close()
                moveTo(25.5f, 31.507f)
                lineTo(27.0f, 31.507f)
                verticalLineToRelative(-3.0f)
                horizontalLineToRelative(-1.5f)
                close()
                moveTo(30.0f, 30.002f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(1.5f)
                lineTo(30.0f, 31.502f)
                verticalLineToRelative(0.005f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-3.0f)
                lineTo(30.0f, 28.507f)
                close()
                moveTo(30.0f, 7.505f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-3.0f)
                lineTo(30.0f, 4.505f)
                verticalLineToRelative(-0.003f)
                horizontalLineToRelative(-3.0f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(3.0f)
                close()
                moveTo(30.0f, 22.505f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(4.497f)
                lineTo(27.0f, 27.002f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(3.0f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-1.5f)
                lineTo(30.0f, 25.502f)
                close()
                moveTo(30.0f, 18.005f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-3.0f)
                lineTo(30.0f, 15.005f)
                close()
                moveTo(25.5f, 10.501f)
                horizontalLineToRelative(3.0f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(-3.0f)
                close()
                moveTo(28.5f, 12.001f)
                verticalLineToRelative(3.004f)
                lineTo(30.0f, 15.005f)
                verticalLineToRelative(-1.5f)
                lineToRelative(1.5f, -0.003f)
                verticalLineToRelative(-1.5f)
                close()
                moveTo(16.5f, 31.503f)
                horizontalLineToRelative(3.0f)
                lineTo(19.5f, 30.0f)
                horizontalLineToRelative(-3.0f)
                close()
                moveTo(15.0f, 12.002f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(0.003f)
                lineTo(18.0f, 12.005f)
                verticalLineToRelative(-3.0f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(1.497f)
                lineTo(15.0f, 10.502f)
                close()
                moveTo(15.0f, 28.502f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(1.5f)
                lineTo(15.0f, 30.002f)
                verticalLineToRelative(0.005f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-3.0f)
                lineTo(15.0f, 27.007f)
                close()
                moveTo(22.5f, 28.507f)
                lineTo(21.0f, 28.507f)
                verticalLineToRelative(3.0f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-0.005f)
                lineTo(24.0f, 31.502f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(-1.5f)
                close()
                moveTo(11.999f, 22.503f)
                lineTo(8.999f, 22.506f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(1.497f)
                horizontalLineToRelative(3.0f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(-1.5f)
                close()
                moveTo(15.0f, 25.503f)
                horizontalLineToRelative(3.0f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(-3.0f)
                close()
                moveTo(24.0f, 16.501f)
                horizontalLineToRelative(3.0f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(-3.0f)
                close()
                moveTo(4.499f, 27.001f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(-1.5f)
                close()
                moveTo(7.499f, 19.501f)
                lineTo(9.0f, 19.501f)
                verticalLineToRelative(-1.5f)
                lineTo(7.499f, 18.001f)
                close()
                moveTo(10.499f, 13.501f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(-1.5f)
                close()
                moveTo(21.0f, 12.003f)
                horizontalLineToRelative(1.5f)
                lineTo(22.5f, 10.5f)
                lineTo(21.0f, 10.5f)
                close()
                moveTo(5.999f, 18.0f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(-1.5f)
                close()
                moveTo(4.499f, 16.5f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-3.0f)
                horizontalLineToRelative(-1.5f)
                close()
                moveTo(4.499f, 21.002f)
                horizontalLineToRelative(1.5f)
                lineTo(5.999f, 18.0f)
                horizontalLineToRelative(-1.5f)
                close()
                moveTo(7.499f, 27.003f)
                lineTo(10.5f, 27.003f)
                verticalLineToRelative(-1.5f)
                lineTo(7.499f, 25.503f)
                close()
                moveTo(7.499f, 21.002f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(1.5f)
                lineToRelative(-1.5f, 0.003f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(3.0f)
                close()
                moveTo(10.499f, 28.502f)
                verticalLineToRelative(0.004f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(1.495f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-2.996f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(-3.0f)
                close()
                moveTo(5.999f, 28.502f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(3.0f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(0.004f)
                horizontalLineToRelative(3.0f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(-3.0f)
                close()
                moveTo(8.999f, 21.005f)
                horizontalLineToRelative(3.0f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(-3.0f)
                close()
                moveTo(8.999f, 18.005f)
                horizontalLineToRelative(3.0f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(-3.0f)
                close()
                moveTo(25.5f, 25.503f)
                lineTo(27.0f, 25.503f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(-1.5f)
                close()
                moveTo(21.0f, 25.503f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(3.0f)
                horizontalLineToRelative(3.0f)
                verticalLineToRelative(-1.5f)
                lineTo(24.0f, 27.003f)
                verticalLineToRelative(-2.997f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-3.0f)
                lineTo(24.0f, 21.006f)
                verticalLineToRelative(2.997f)
                lineToRelative(-4.5f, 0.003f)
                verticalLineToRelative(1.5f)
                lineTo(18.0f, 25.506f)
                verticalLineToRelative(3.0f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-1.5f)
                lineTo(21.0f, 27.006f)
                close()
            }
        }
        .build()
        return _qrcodeMedium!!
    }

private var _qrcodeMedium: ImageVector? = null
