package ch.sbb.compose_mds.sbbicons.medium

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType.Companion.EvenOdd
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap.Companion.Butt
import androidx.compose.ui.graphics.StrokeJoin.Companion.Miter
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.ImageVector.Builder
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import ch.sbb.compose_mds.sbbicons.MediumGroup

public val MediumGroup.QrcodeDisabledMedium: ImageVector
    get() {
        if (_qrcodeDisabledMedium != null) {
            return _qrcodeDisabledMedium!!
        }
        _qrcodeDisabledMedium = Builder(name = "QrcodeDisabledMedium", defaultWidth = 36.0.dp,
                defaultHeight = 36.0.dp, viewportWidth = 36.0f, viewportHeight = 36.0f).apply {
            path(fill = SolidColor(Color(0xFF000000)), stroke = null, strokeLineWidth = 0.0f,
                    strokeLineCap = Butt, strokeLineJoin = Miter, strokeLineMiter = 4.0f,
                    pathFillType = EvenOdd) {
                moveToRelative(30.95f, 31.507f)
                lineToRelative(0.197f, 0.197f)
                lineToRelative(0.196f, -0.197f)
                horizontalLineToRelative(0.157f)
                verticalLineToRelative(-0.157f)
                lineToRelative(0.354f, -0.354f)
                lineToRelative(-0.354f, -0.353f)
                verticalLineToRelative(-0.023f)
                lineToRelative(-1.5f, -1.5f)
                verticalLineToRelative(0.023f)
                lineToRelative(-0.64f, -0.64f)
                horizontalLineToRelative(0.022f)
                lineToRelative(-1.5f, -1.5f)
                horizontalLineToRelative(-0.023f)
                lineToRelative(-1.5f, -1.5f)
                horizontalLineToRelative(0.023f)
                lineToRelative(-0.882f, -0.883f)
                verticalLineToRelative(0.023f)
                lineToRelative(-0.637f, -0.637f)
                horizontalLineToRelative(0.022f)
                lineTo(24.0f, 23.12f)
                verticalLineToRelative(0.023f)
                lineToRelative(-1.5f, -1.5f)
                verticalLineToRelative(-0.023f)
                lineToRelative(-1.5f, -1.5f)
                verticalLineToRelative(0.023f)
                lineToRelative(-1.5f, -1.5f)
                verticalLineToRelative(-0.022f)
                lineToRelative(-2.122f, -2.12f)
                horizontalLineToRelative(-0.02f)
                lineToRelative(-1.501f, -1.502f)
                horizontalLineToRelative(0.022f)
                lineToRelative(-1.5f, -1.5f)
                horizontalLineToRelative(-0.022f)
                lineToRelative(-2.996f, -2.995f)
                horizontalLineToRelative(0.023f)
                lineTo(8.378f, 7.5f)
                horizontalLineToRelative(-0.021f)
                lineTo(6.859f, 6.002f)
                horizontalLineToRelative(0.02f)
                lineTo(5.372f, 4.493f)
                lineTo(5.35f, 4.493f)
                lineToRelative(-0.346f, -0.347f)
                lineToRelative(-0.347f, 0.347f)
                lineTo(4.5f, 4.493f)
                verticalLineToRelative(0.159f)
                lineToRelative(-0.202f, 0.202f)
                lineToRelative(0.202f, 0.202f)
                verticalLineToRelative(2.449f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-0.95f)
                lineToRelative(1.5f, 1.5f)
                lineTo(7.5f, 9.0f)
                lineToRelative(0.946f, 0.002f)
                lineToRelative(0.554f, 0.554f)
                verticalLineToRelative(2.448f)
                horizontalLineToRelative(1.5f)
                lineTo(10.5f, 13.5f)
                lineTo(7.5f, 13.5f)
                verticalLineToRelative(-3.0f)
                lineTo(6.0f, 10.5f)
                lineTo(6.0f, 9.0f)
                lineTo(4.5f, 9.0f)
                verticalLineToRelative(3.0f)
                lineTo(6.0f, 12.0f)
                verticalLineToRelative(1.5f)
                lineTo(7.5f, 13.5f)
                lineTo(7.5f, 15.0f)
                horizontalLineToRelative(3.0f)
                verticalLineToRelative(-1.498f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-0.947f)
                lineToRelative(1.501f, 1.502f)
                lineTo(13.501f, 22.5f)
                horizontalLineToRelative(8.443f)
                lineToRelative(1.503f, 1.503f)
                lineToRelative(-3.946f, 0.003f)
                verticalLineToRelative(1.5f)
                lineTo(18.0f, 25.506f)
                verticalLineToRelative(3.0f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-1.5f)
                lineTo(21.0f, 27.006f)
                verticalLineToRelative(-1.503f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(3.0f)
                horizontalLineToRelative(3.0f)
                verticalLineToRelative(-1.5f)
                lineTo(24.0f, 27.003f)
                verticalLineToRelative(-2.446f)
                lineToRelative(3.0f, 3.0f)
                verticalLineToRelative(0.945f)
                horizontalLineToRelative(0.945f)
                lineToRelative(1.5f, 1.5f)
                lineTo(28.5f, 30.002f)
                verticalLineToRelative(1.5f)
                lineTo(30.0f, 31.502f)
                verticalLineToRelative(0.005f)
                close()
                moveTo(20.443f, 21.0f)
                lineToRelative(-1.5f, -1.5f)
                lineTo(16.5f, 19.5f)
                verticalLineToRelative(-2.443f)
                lineToRelative(-1.5f, -1.5f)
                lineTo(15.0f, 21.0f)
                close()
                moveTo(11.444f, 12.002f)
                lineTo(10.499f, 11.055f)
                verticalLineToRelative(0.947f)
                close()
                moveTo(10.5f, 5.379f)
                verticalLineToRelative(-0.887f)
                horizontalLineToRelative(4.502f)
                verticalLineToRelative(1.502f)
                horizontalLineToRelative(-3.887f)
                close()
                moveTo(21.0f, 15.879f)
                lineTo(21.0f, 15.0f)
                horizontalLineToRelative(-0.879f)
                lineToRelative(-1.5f, -1.5f)
                horizontalLineToRelative(3.88f)
                verticalLineToRelative(3.88f)
                close()
                moveTo(13.5f, 7.502f)
                verticalLineToRelative(0.003f)
                horizontalLineToRelative(-0.873f)
                lineToRelative(1.497f, 1.497f)
                lineTo(16.5f, 9.002f)
                verticalLineToRelative(-1.5f)
                lineTo(18.0f, 7.502f)
                verticalLineToRelative(0.003f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(3.0f)
                lineTo(21.0f, 10.505f)
                verticalLineToRelative(-1.5f)
                lineToRelative(4.5f, -0.003f)
                verticalLineToRelative(-1.5f)
                lineTo(27.0f, 7.502f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(-1.5f)
                lineTo(25.5f, 4.505f)
                lineTo(24.0f, 4.505f)
                verticalLineToRelative(2.997f)
                horizontalLineToRelative(-1.5f)
                lineTo(22.5f, 6.005f)
                lineTo(21.0f, 6.005f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(-3.0f)
                lineTo(18.0f, 4.505f)
                verticalLineToRelative(1.497f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(1.5f)
                close()
                moveTo(30.0f, 10.505f)
                horizontalLineToRelative(1.5f)
                lineTo(31.5f, 9.003f)
                lineTo(30.0f, 9.003f)
                close()
                moveTo(27.0f, 18.005f)
                verticalLineToRelative(1.497f)
                horizontalLineToRelative(-2.377f)
                lineTo(24.0f, 18.879f)
                verticalLineToRelative(-0.877f)
                horizontalLineToRelative(3.0f)
                verticalLineToRelative(-1.497f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(1.5f)
                close()
                moveTo(28.5f, 21.005f)
                verticalLineToRelative(1.5f)
                lineTo(30.0f, 22.505f)
                verticalLineToRelative(2.373f)
                lineToRelative(-1.5f, -1.5f)
                verticalLineToRelative(-0.873f)
                horizontalLineToRelative(-0.873f)
                lineTo(27.0f, 21.878f)
                verticalLineToRelative(-2.373f)
                horizontalLineToRelative(4.5f)
                verticalLineToRelative(3.0f)
                lineTo(30.0f, 22.505f)
                verticalLineToRelative(-1.5f)
                close()
                moveTo(25.5f, 12.002f)
                lineTo(27.0f, 12.002f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(0.003f)
                lineTo(24.0f, 13.505f)
                verticalLineToRelative(-3.0f)
                horizontalLineToRelative(1.5f)
                close()
                moveTo(25.5f, 31.507f)
                lineTo(27.0f, 31.507f)
                verticalLineToRelative(-3.0f)
                horizontalLineToRelative(-1.5f)
                close()
                moveTo(30.0f, 7.506f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-3.0f)
                lineTo(30.0f, 4.506f)
                verticalLineToRelative(-0.003f)
                horizontalLineToRelative(-3.0f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(3.0f)
                close()
                moveTo(31.5f, 26.379f)
                lineTo(30.624f, 25.503f)
                horizontalLineToRelative(0.876f)
                close()
                moveTo(30.0f, 18.006f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-3.001f)
                lineTo(30.0f, 15.005f)
                verticalLineToRelative(-1.5f)
                lineToRelative(1.5f, -0.003f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(-3.0f)
                verticalLineToRelative(3.003f)
                lineTo(30.0f, 15.005f)
                close()
                moveTo(28.5f, 10.502f)
                horizontalLineToRelative(-3.0f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(3.0f)
                close()
                moveTo(16.5f, 31.503f)
                verticalLineToRelative(-1.501f)
                horizontalLineToRelative(3.0f)
                verticalLineToRelative(1.501f)
                close()
                moveTo(18.0f, 12.005f)
                verticalLineToRelative(-3.0f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(1.497f)
                horizontalLineToRelative(-0.878f)
                lineToRelative(1.503f, 1.503f)
                close()
                moveTo(13.5f, 28.503f)
                lineTo(15.0f, 28.503f)
                verticalLineToRelative(-1.496f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(3.0f)
                lineTo(15.0f, 30.007f)
                verticalLineToRelative(-0.004f)
                horizontalLineToRelative(-1.5f)
                close()
                moveTo(22.5f, 28.507f)
                lineTo(21.0f, 28.507f)
                verticalLineToRelative(3.0f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-0.005f)
                lineTo(24.0f, 31.502f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(-1.5f)
                close()
                moveTo(9.0f, 24.006f)
                verticalLineToRelative(-1.5f)
                lineToRelative(3.0f, -0.003f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(-3.0f)
                verticalLineToRelative(-1.497f)
                close()
                moveTo(15.0f, 24.003f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(3.0f)
                verticalLineToRelative(-1.5f)
                close()
                moveTo(27.0f, 16.502f)
                horizontalLineToRelative(-3.0f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(3.0f)
                close()
                moveTo(4.5f, 27.002f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(-1.5f)
                close()
                moveTo(9.0f, 19.502f)
                lineTo(7.5f, 19.502f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-1.496f)
                horizontalLineToRelative(3.0f)
                verticalLineToRelative(1.5f)
                lineTo(9.0f, 18.006f)
                close()
                moveTo(6.0f, 18.002f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(-3.0f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(3.0f)
                horizontalLineToRelative(1.5f)
                close()
                moveTo(6.0f, 18.002f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(3.001f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(1.5f)
                lineToRelative(-1.5f, 0.003f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(3.0f)
                verticalLineToRelative(-3.003f)
                horizontalLineToRelative(-1.5f)
                close()
                moveTo(22.5f, 12.003f)
                lineTo(21.0f, 12.003f)
                verticalLineToRelative(-1.501f)
                horizontalLineToRelative(1.5f)
                close()
                moveTo(10.5f, 27.005f)
                lineTo(7.5f, 27.005f)
                verticalLineToRelative(-1.5f)
                lineTo(10.5f, 25.505f)
                close()
                moveTo(10.499f, 28.505f)
                verticalLineToRelative(-1.499f)
                horizontalLineToRelative(3.0f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(2.997f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(-1.496f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(1.5f)
                close()
                moveTo(5.999f, 30.007f)
                horizontalLineToRelative(3.0f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(-3.0f)
                verticalLineToRelative(-0.005f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(-3.0f)
                horizontalLineToRelative(1.5f)
                close()
                moveTo(11.999f, 21.006f)
                horizontalLineToRelative(-3.0f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(3.0f)
                close()
            }
        }
        .build()
        return _qrcodeDisabledMedium!!
    }

private var _qrcodeDisabledMedium: ImageVector? = null
