package ch.sbb.compose_mds.sbbicons.medium

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType.Companion.EvenOdd
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap.Companion.Butt
import androidx.compose.ui.graphics.StrokeJoin.Companion.Miter
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.ImageVector.Builder
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import ch.sbb.compose_mds.sbbicons.MediumGroup

public val MediumGroup.QrcodeTwoTicketsMedium: ImageVector
    get() {
        if (_qrcodeTwoTicketsMedium != null) {
            return _qrcodeTwoTicketsMedium!!
        }
        _qrcodeTwoTicketsMedium = Builder(name = "QrcodeTwoTicketsMedium", defaultWidth = 36.0.dp,
                defaultHeight = 36.0.dp, viewportWidth = 36.0f, viewportHeight = 36.0f).apply {
            path(fill = SolidColor(Color(0xFF000000)), stroke = null, strokeLineWidth = 0.0f,
                    strokeLineCap = Butt, strokeLineJoin = Miter, strokeLineMiter = 4.0f,
                    pathFillType = EvenOdd) {
                moveTo(4.5f, 4.5f)
                lineTo(4.5f, 9.0f)
                lineTo(6.0f, 9.0f)
                lineTo(6.0f, 5.992f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(-3.0f)
                close()
                moveTo(4.5f, 11.994f)
                horizontalLineToRelative(3.002f)
                verticalLineToRelative(-1.5f)
                lineTo(4.5f, 10.494f)
                close()
                moveTo(15.0f, 7.5f)
                horizontalLineToRelative(-1.501f)
                verticalLineToRelative(-1.5f)
                lineTo(15.0f, 6.0f)
                close()
                moveTo(16.502f, 7.5f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-3.0f)
                horizontalLineToRelative(-1.5f)
                close()
                moveTo(8.999f, 4.496f)
                horizontalLineToRelative(4.5f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(-3.0f)
                verticalLineToRelative(1.503f)
                horizontalLineToRelative(-3.0f)
                verticalLineToRelative(-1.5f)
                lineTo(9.0f, 5.999f)
                lineTo(9.0f, 4.496f)
                moveToRelative(10.503f, 3.0f)
                horizontalLineToRelative(3.0f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-3.0f)
                horizontalLineToRelative(-3.0f)
                verticalLineToRelative(1.498f)
                horizontalLineToRelative(-3.0f)
                close()
                moveTo(6.0f, 25.5f)
                lineTo(4.5f, 25.5f)
                verticalLineToRelative(-3.0f)
                lineTo(6.0f, 22.5f)
                close()
                moveTo(4.5f, 16.497f)
                lineTo(6.0f, 16.497f)
                lineTo(6.0f, 15.0f)
                horizontalLineToRelative(1.502f)
                verticalLineToRelative(-1.5f)
                lineTo(6.0f, 13.5f)
                verticalLineToRelative(1.497f)
                lineTo(4.5f, 14.997f)
                close()
                moveTo(6.0f, 19.496f)
                lineTo(4.5f, 19.496f)
                verticalLineToRelative(-1.502f)
                lineTo(6.0f, 17.994f)
                lineTo(6.0f, 16.5f)
                horizontalLineToRelative(1.502f)
                lineTo(7.502f, 18.0f)
                lineTo(6.0f, 18.0f)
                close()
                moveTo(7.502f, 21.0f)
                lineTo(6.0f, 21.0f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(1.502f)
                close()
                moveTo(16.5f, 25.496f)
                horizontalLineToRelative(9.0f)
                verticalLineToRelative(-9.0f)
                horizontalLineToRelative(-9.0f)
                close()
                moveTo(18.0f, 23.994f)
                horizontalLineToRelative(6.0f)
                verticalLineToRelative(-6.0f)
                horizontalLineToRelative(-6.0f)
                close()
                moveTo(22.5f, 22.496f)
                horizontalLineToRelative(-3.0f)
                verticalLineToRelative(-3.0f)
                horizontalLineToRelative(3.0f)
                close()
                moveTo(10.499f, 17.996f)
                horizontalLineToRelative(3.0f)
                verticalLineToRelative(-1.499f)
                lineTo(15.0f, 16.497f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(-1.501f)
                verticalLineToRelative(1.499f)
                horizontalLineToRelative(-3.0f)
                close()
                moveTo(21.002f, 14.997f)
                lineTo(21.002f, 15.0f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(-0.003f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(1.5f)
                lineTo(19.502f, 12.0f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(2.997f)
                moveToRelative(10.5f, 4.503f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(1.497f)
                horizontalLineToRelative(-3.0f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(3.0f)
                lineTo(30.002f, 21.0f)
                horizontalLineToRelative(1.5f)
                close()
                moveTo(30.002f, 16.5f)
                horizontalLineToRelative(1.5f)
                lineTo(31.502f, 18.0f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(1.497f)
                horizontalLineToRelative(-3.0f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(3.0f)
                close()
                moveTo(16.499f, 13.5f)
                verticalLineToRelative(-1.503f)
                horizontalLineToRelative(3.002f)
                verticalLineToRelative(-1.5f)
                lineTo(15.0f, 10.497f)
                verticalLineToRelative(0.003f)
                horizontalLineToRelative(-0.002f)
                lineTo(14.998f, 12.0f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(1.5f)
                close()
                moveTo(24.0f, 13.5f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(-3.0f)
                lineTo(24.0f, 10.5f)
                verticalLineToRelative(2.997f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(1.5f)
                lineTo(24.0f, 14.997f)
                close()
                moveTo(30.002f, 25.5f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-3.0f)
                horizontalLineToRelative(-1.5f)
                close()
                moveTo(13.499f, 11.994f)
                lineTo(12.0f, 11.994f)
                lineTo(12.0f, 15.0f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(-4.506f)
                horizontalLineToRelative(3.0f)
                close()
                moveTo(18.001f, 31.502f)
                horizontalLineToRelative(1.502f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(-1.501f)
                close()
                moveTo(11.998f, 31.502f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(-3.003f)
                horizontalLineToRelative(1.5f)
                close()
                moveTo(15.0f, 25.497f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(0.003f)
                lineTo(12.0f, 25.5f)
                lineTo(12.0f, 27.0f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(1.497f)
                horizontalLineToRelative(3.002f)
                verticalLineToRelative(-1.5f)
                lineTo(15.0f, 26.997f)
                close()
                moveTo(21.004f, 28.497f)
                horizontalLineToRelative(-3.001f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(3.001f)
                close()
                moveTo(30.003f, 31.497f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(-1.5f)
                close()
                moveTo(12.0f, 22.497f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(1.5f)
                lineTo(12.0f, 19.5f)
                lineTo(15.0f, 19.5f)
                lineTo(15.0f, 21.0f)
                horizontalLineToRelative(-3.001f)
                close()
                moveTo(10.5f, 25.497f)
                horizontalLineToRelative(1.5f)
                lineTo(12.0f, 24.0f)
                lineTo(15.0f, 24.0f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(-3.001f)
                verticalLineToRelative(1.497f)
                horizontalLineToRelative(-1.5f)
                close()
                moveTo(31.502f, 13.497f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(3.0f)
                verticalLineToRelative(3.0f)
                moveTo(13.5f, 31.501f)
                lineTo(16.5f, 31.501f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(-3.001f)
                close()
                moveTo(30.0f, 28.497f)
                horizontalLineToRelative(-1.5f)
                lineTo(28.5f, 27.0f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(2.997f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(-3.0f)
                verticalLineToRelative(-3.0f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(1.505f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(-3.0f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-1.5f)
                lineToRelative(4.5f, -0.005f)
                lineTo(27.0f, 24.0f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(2.997f)
                horizontalLineToRelative(1.5f)
                close()
                moveTo(27.0f, 16.5f)
                verticalLineToRelative(-3.0f)
                lineToRelative(-1.5f, -0.003f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(3.0f)
                verticalLineToRelative(3.0f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(1.5f)
                close()
            }
        }
        .build()
        return _qrcodeTwoTicketsMedium!!
    }

private var _qrcodeTwoTicketsMedium: ImageVector? = null
