package ch.sbb.compose_mds.sbbicons.medium

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType.Companion.EvenOdd
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap.Companion.Butt
import androidx.compose.ui.graphics.StrokeJoin.Companion.Miter
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.ImageVector.Builder
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import ch.sbb.compose_mds.sbbicons.MediumGroup

public val MediumGroup.QrcodeDisabledTwoTicketsMedium: ImageVector
    get() {
        if (_qrcodeDisabledTwoTicketsMedium != null) {
            return _qrcodeDisabledTwoTicketsMedium!!
        }
        _qrcodeDisabledTwoTicketsMedium = Builder(name = "QrcodeDisabledTwoTicketsMedium",
                defaultWidth = 36.0.dp, defaultHeight = 36.0.dp, viewportWidth = 36.0f,
                viewportHeight = 36.0f).apply {
            path(fill = SolidColor(Color(0xFF000000)), stroke = null, strokeLineWidth = 0.0f,
                    strokeLineCap = Butt, strokeLineJoin = Miter, strokeLineMiter = 4.0f,
                    pathFillType = EvenOdd) {
                moveToRelative(31.854f, 31.147f)
                lineToRelative(-27.0f, -27.0f)
                lineTo(4.5f, 4.5f)
                lineToRelative(-0.354f, 0.354f)
                lineToRelative(0.354f, 0.353f)
                lineTo(4.5f, 9.0f)
                lineTo(6.0f, 9.0f)
                lineTo(6.0f, 6.707f)
                lineToRelative(4.5f, 4.5f)
                lineTo(10.5f, 15.0f)
                lineTo(12.0f, 15.0f)
                verticalLineToRelative(-2.294f)
                lineToRelative(2.29f, 2.291f)
                horizontalLineToRelative(-0.791f)
                verticalLineToRelative(1.499f)
                horizontalLineToRelative(-3.0f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(3.0f)
                verticalLineToRelative(-1.499f)
                lineTo(15.0f, 16.497f)
                verticalLineToRelative(-0.79f)
                lineToRelative(1.5f, 1.5f)
                lineTo(16.5f, 25.5f)
                horizontalLineToRelative(8.293f)
                lineToRelative(1.5f, 1.5f)
                lineToRelative(-3.791f, 0.002f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(3.0f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-1.505f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(3.0f)
                horizontalLineToRelative(3.0f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(-2.288f)
                lineToRelative(3.0f, 3.0f)
                verticalLineToRelative(0.787f)
                horizontalLineToRelative(0.787f)
                lineToRelative(0.357f, 0.358f)
                close()
                moveTo(23.293f, 24.0f)
                lineToRelative(-1.505f, -1.504f)
                lineTo(19.5f, 22.496f)
                verticalLineToRelative(-2.289f)
                lineToRelative(-1.5f, -1.5f)
                lineTo(18.0f, 24.0f)
                close()
                moveTo(4.5f, 11.994f)
                horizontalLineToRelative(3.002f)
                verticalLineToRelative(-1.5f)
                lineTo(4.5f, 10.494f)
                close()
                moveTo(15.0f, 7.5f)
                lineTo(13.5f, 7.5f)
                verticalLineToRelative(-1.5f)
                lineTo(15.0f, 6.0f)
                close()
                moveTo(16.502f, 7.5f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-3.0f)
                horizontalLineToRelative(-1.5f)
                close()
                moveTo(22.502f, 7.497f)
                horizontalLineToRelative(-3.0f)
                lineTo(19.502f, 5.994f)
                horizontalLineToRelative(3.0f)
                lineTo(22.502f, 4.496f)
                horizontalLineToRelative(3.0f)
                verticalLineToRelative(3.0f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(-1.5f)
                close()
                moveTo(4.5f, 25.5f)
                lineTo(6.0f, 25.5f)
                verticalLineToRelative(-3.0f)
                lineTo(4.5f, 22.5f)
                close()
                moveTo(6.0f, 16.497f)
                lineTo(4.5f, 16.497f)
                verticalLineToRelative(-1.5f)
                lineTo(6.0f, 14.997f)
                lineTo(6.0f, 13.5f)
                horizontalLineToRelative(1.502f)
                lineTo(7.502f, 15.0f)
                lineTo(6.0f, 15.0f)
                close()
                moveTo(4.5f, 19.496f)
                lineTo(6.0f, 19.496f)
                lineTo(6.0f, 18.0f)
                horizontalLineToRelative(1.502f)
                verticalLineToRelative(-1.5f)
                lineTo(6.0f, 16.5f)
                verticalLineToRelative(1.494f)
                lineTo(4.5f, 17.994f)
                close()
                moveTo(6.0f, 21.0f)
                horizontalLineToRelative(1.502f)
                verticalLineToRelative(-1.5f)
                lineTo(6.0f, 19.5f)
                close()
                moveTo(31.502f, 19.5f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(1.497f)
                horizontalLineToRelative(-3.0f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(3.0f)
                lineTo(30.002f, 21.0f)
                horizontalLineToRelative(1.5f)
                close()
                moveTo(30.002f, 16.5f)
                horizontalLineToRelative(1.5f)
                lineTo(31.502f, 18.0f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(1.497f)
                horizontalLineToRelative(-3.0f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(3.0f)
                close()
                moveTo(22.5f, 13.5f)
                lineTo(24.0f, 13.5f)
                verticalLineToRelative(1.497f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-1.5f)
                lineTo(24.0f, 13.497f)
                lineTo(24.0f, 10.5f)
                horizontalLineToRelative(-1.5f)
                close()
                moveTo(31.502f, 25.5f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(-3.0f)
                horizontalLineToRelative(1.5f)
                close()
                moveTo(19.503f, 31.502f)
                horizontalLineToRelative(-1.501f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(1.501f)
                close()
                moveTo(10.499f, 31.502f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-3.003f)
                horizontalLineToRelative(-1.5f)
                close()
                moveTo(13.499f, 25.497f)
                lineTo(15.0f, 25.497f)
                lineToRelative(0.002f, 1.5f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(-3.002f)
                lineTo(13.5f, 27.0f)
                lineTo(12.0f, 27.0f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(1.5f)
                close()
                moveTo(18.001f, 28.497f)
                horizontalLineToRelative(3.002f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(-3.001f)
                close()
                moveTo(10.499f, 22.497f)
                horizontalLineToRelative(1.5f)
                lineTo(11.999f, 21.0f)
                lineTo(15.0f, 21.0f)
                verticalLineToRelative(-1.5f)
                lineTo(12.0f, 19.5f)
                verticalLineToRelative(1.497f)
                horizontalLineToRelative(-1.5f)
                close()
                moveTo(11.999f, 25.497f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(1.5f)
                lineTo(11.999f, 22.5f)
                lineTo(15.0f, 22.5f)
                lineTo(15.0f, 24.0f)
                lineTo(12.0f, 24.0f)
                close()
                moveTo(30.001f, 13.497f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-3.0f)
                horizontalLineToRelative(-3.0f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(1.5f)
                close()
                moveTo(16.501f, 31.502f)
                horizontalLineToRelative(-3.002f)
                verticalLineToRelative(-1.5f)
                lineTo(16.5f, 30.002f)
                close()
                moveTo(27.0f, 16.5f)
                verticalLineToRelative(-3.0f)
                lineToRelative(-1.5f, -0.003f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(3.0f)
                verticalLineToRelative(3.0f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(1.5f)
                close()
                moveTo(22.493f, 17.994f)
                lineTo(24.0f, 17.994f)
                lineTo(24.0f, 19.5f)
                lineToRelative(1.5f, 1.5f)
                verticalLineToRelative(-4.504f)
                horizontalLineToRelative(-4.504f)
                close()
                moveTo(19.5f, 14.997f)
                horizontalLineToRelative(-0.003f)
                lineTo(18.0f, 13.5f)
                verticalLineToRelative(-0.003f)
                horizontalLineToRelative(1.5f)
                lineTo(19.5f, 12.0f)
                lineTo(21.0f, 12.0f)
                verticalLineToRelative(3.0f)
                horizontalLineToRelative(-1.5f)
                close()
                moveTo(16.5f, 11.999f)
                verticalLineToRelative(-0.001f)
                horizontalLineToRelative(3.0f)
                verticalLineToRelative(-1.5f)
                lineTo(15.0f, 10.498f)
                verticalLineToRelative(0.001f)
                close()
                moveTo(10.5f, 5.996f)
                lineTo(10.5f, 6.0f)
                lineTo(9.0f, 4.5f)
                verticalLineToRelative(-0.003f)
                horizontalLineToRelative(4.5f)
                verticalLineToRelative(1.5f)
                close()
            }
        }
        .build()
        return _qrcodeDisabledTwoTicketsMedium!!
    }

private var _qrcodeDisabledTwoTicketsMedium: ImageVector? = null
