package ch.sbb.compose_mds.sbbicons.medium

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType.Companion.EvenOdd
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap.Companion.Butt
import androidx.compose.ui.graphics.StrokeJoin.Companion.Miter
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.ImageVector.Builder
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import ch.sbb.compose_mds.sbbicons.MediumGroup

public val MediumGroup.TicketJourneyMedium: ImageVector
    get() {
        if (_ticketJourneyMedium != null) {
            return _ticketJourneyMedium!!
        }
        _ticketJourneyMedium = Builder(name = "TicketJourneyMedium", defaultWidth = 36.0.dp,
                defaultHeight = 36.0.dp, viewportWidth = 36.0f, viewportHeight = 36.0f).apply {
            path(fill = SolidColor(Color(0xFF000000)), stroke = null, strokeLineWidth = 0.0f,
                    strokeLineCap = Butt, strokeLineJoin = Miter, strokeLineMiter = 4.0f,
                    pathFillType = EvenOdd) {
                moveTo(23.989f, 4.76f)
                arcToRelative(7.25f, 7.25f, 0.0f, false, false, -7.25f, 7.25f)
                verticalLineToRelative(0.02f)
                curveToRelative(0.021f, 0.561f, 0.109f, 1.084f, 0.252f, 1.58f)
                lineToRelative(0.96f, -0.277f)
                arcToRelative(5.6f, 5.6f, 0.0f, false, true, -0.212f, -1.332f)
                arcToRelative(6.25f, 6.25f, 0.0f, false, true, 12.5f, 0.007f)
                curveToRelative(-0.01f, 0.993f, -0.32f, 1.897f, -0.83f, 2.796f)
                lineToRelative(-5.402f, 8.526f)
                lineToRelative(-1.115f, -1.76f)
                lineToRelative(-0.845f, 0.535f)
                lineToRelative(1.537f, 2.427f)
                lineToRelative(0.423f, 0.666f)
                lineToRelative(0.422f, -0.666f)
                lineToRelative(5.83f, -9.203f)
                lineToRelative(0.007f, -0.01f)
                lineToRelative(0.006f, -0.01f)
                curveToRelative(0.572f, -1.005f, 0.955f, -2.08f, 0.967f, -3.293f)
                verticalLineToRelative(-0.005f)
                arcToRelative(7.25f, 7.25f, 0.0f, false, false, -7.25f, -7.25f)
                moveToRelative(0.01f, 5.491f)
                arcToRelative(1.749f, 1.749f, 0.0f, true, false, 0.0f, 3.5f)
                arcToRelative(1.75f, 1.75f, 0.0f, true, false, 0.0f, -3.5f)
                moveToRelative(-2.75f, 1.75f)
                arcToRelative(2.749f, 2.749f, 0.0f, true, true, 5.5f, 0.0f)
                arcToRelative(2.75f, 2.75f, 0.0f, true, true, -5.5f, 0.0f)
                moveTo(7.498f, 16.5f)
                lineTo(6.0f, 16.5f)
                verticalLineToRelative(1.49f)
                lineTo(4.489f, 17.99f)
                verticalLineToRelative(-3.0f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-0.002f)
                lineTo(7.5f, 14.988f)
                close()
                moveTo(5.989f, 31.491f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(-3.0f)
                lineTo(6.0f, 28.491f)
                verticalLineToRelative(1.499f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(1.512f)
                lineTo(5.988f, 31.502f)
                close()
                moveTo(10.489f, 28.49f)
                verticalLineToRelative(-1.5f)
                lineTo(7.5f, 26.99f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(-0.012f)
                verticalLineToRelative(-1.488f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(2.986f)
                horizontalLineToRelative(7.5f)
                verticalLineToRelative(-2.986f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(1.488f)
                horizontalLineToRelative(-1.499f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(-3.0f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(2.999f)
                verticalLineToRelative(1.512f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(1.5f)
                lineTo(19.5f, 31.502f)
                verticalLineToRelative(-0.011f)
                lineTo(21.0f, 31.491f)
                verticalLineToRelative(-3.0f)
                lineTo(19.49f, 28.491f)
                verticalLineToRelative(1.499f)
                lineTo(18.0f, 29.99f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(-1.51f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(3.002f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(1.498f)
                verticalLineToRelative(-1.5f)
                lineTo(18.0f, 23.99f)
                lineTo(18.0f, 22.49f)
                horizontalLineToRelative(2.99f)
                verticalLineToRelative(-1.5f)
                lineTo(19.5f, 20.99f)
                lineTo(19.5f, 19.49f)
                horizontalLineToRelative(-1.51f)
                lineTo(17.99f, 18.0f)
                lineTo(18.0f, 18.0f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(1.49f)
                verticalLineToRelative(1.49f)
                horizontalLineToRelative(1.512f)
                verticalLineToRelative(-3.0f)
                lineTo(19.5f, 14.99f)
                verticalLineToRelative(-0.002f)
                horizontalLineToRelative(-1.512f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(1.502f)
                horizontalLineToRelative(-1.499f)
                verticalLineToRelative(1.498f)
                lineTo(13.5f, 19.488f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(-1.511f)
                lineTo(11.989f, 16.49f)
                horizontalLineToRelative(-3.0f)
                verticalLineToRelative(1.498f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(1.502f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(1.512f)
                lineTo(6.0f, 22.502f)
                lineTo(6.0f, 20.99f)
                horizontalLineToRelative(2.988f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(-1.5f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(-3.0f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(1.512f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(1.488f)
                close()
                moveTo(10.489f, 28.49f)
                lineTo(12.0f, 28.49f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(2.99f)
                verticalLineToRelative(1.5f)
                horizontalLineToRelative(-3.0f)
                verticalLineToRelative(-1.488f)
                lineTo(10.5f, 30.002f)
                verticalLineToRelative(1.5f)
                lineTo(8.988f, 31.502f)
                lineTo(8.988f, 29.99f)
                horizontalLineToRelative(1.5f)
                close()
                moveTo(9.0f, 19.487f)
                horizontalLineToRelative(2.988f)
                lineTo(11.988f, 17.99f)
                lineTo(9.0f, 17.99f)
                close()
                moveTo(16.488f, 22.489f)
                horizontalLineToRelative(1.5f)
                verticalLineToRelative(-3.0f)
                horizontalLineToRelative(-1.5f)
                close()
                moveTo(11.989f, 16.489f)
                horizontalLineToRelative(3.0f)
                verticalLineToRelative(-1.5f)
                horizontalLineToRelative(-3.0f)
                close()
                moveTo(11.988f, 24.001f)
                lineTo(13.5f, 24.001f)
                lineTo(13.5f, 22.49f)
                horizontalLineToRelative(-1.512f)
                close()
                moveTo(14.988f, 25.487f)
                horizontalLineToRelative(-4.5f)
                verticalLineToRelative(-4.5f)
                horizontalLineToRelative(4.5f)
                close()
            }
        }
        .build()
        return _ticketJourneyMedium!!
    }

private var _ticketJourneyMedium: ImageVector? = null
